se añaden modulos para agregar,actualizar producto y se se deben modificar las funciones de update_task_window
PS C:\Users\Magic1540\Desktop\Portafolio\proyecto\app_python> python -d .\main.py
Traceback (most recent call last):
  File "C:\Users\Magic1540\Desktop\Portafolio\proyecto\app_python\main.py", line 167, in update_products_window
    update_product_window = UpdateProductsWindow()
TypeError: __init__() missing 1 required positional argument: 'product_id'